name: installer-sync
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  installer-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check nanorc included every *nanorc files
        run: |
          ./tools/include-list-gen.sh
          git diff --exit-code src/nanorc || exit 1
